services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - PORT=3000
      - DB_CONNECTION=postgres
      - TEST=${TEST}

  database:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: bind
        source: ./initdb/pg.sql
        target: /docker-entrypoint-initdb.d/pg.sql
        read_only: true  # Ensure this file is read-only
    environment:
      - POSTGRES_USER=myuser     # Specify user if needed
      - POSTGRES_PASSWORD=mypassword  # Set the password
    # Note: POSTGRES_DB is removed
